CREATE TYPE gender AS ENUM ('M', 'F', 'U');

CREATE TYPE voter_status AS ENUM ('A', 'I');

CREATE TYPE vote_method AS ENUM ('AP', 'AB', 'P');

CREATE TABLE voters(
  voter_id varchar(12) PRIMARY KEY,
  title text,
  last_name text,
  first_name text,
  middle_name text,
  suffix text,
  gender gender,
  dob date,
  registration_date date,
  voter_status voter_status,
  status_change_date date,
  party_code text REFERENCES political_parties (code),
  house_number text,
  house_number_suffix text,
  street_name text,
  apartment_number text,
  address_line_2 text,
  city text,
  state text,
  zip_code text,
  mail_address_1 text,
  mail_address_2 text,
  mail_city text,
  mail_state text,
  mail_zip_code text,
  last_vote_date date,
  precinct_code text,
  precinct_split_id text,
  date_last_changed date,
  custom_data_1 text,
  district_1 text,
  district_2 text,
  district_3 text,
  district_4 text,
  district_5 text,
  district_6 text,
  district_7 text,
  district_8 text,
  district_9 text,
  district_10 text,
  district_11 text,
  district_12 text,
  district_13 text,
  district_14 text,
  district_15 text,
  district_16 text,
  district_17 text,
  district_18 text,
  district_19 text,
  district_20 text,
  district_21 text,
  district_22 text,
  district_23 text,
  district_24 text,
  district_25 text,
  district_26 text,
  district_27 text,
  district_28 text,
  district_29 text,
  district_30 text,
  district_31 text,
  district_32 text,
  district_33 text,
  district_34 text,
  district_35 text,
  district_36 text,
  district_37 text,
  district_38 text,
  district_39 text,
  district_40 text,
  election_1_vote_method vote_method,
  election_1_party text REFERENCES political_parties (code),
  election_2_vote_method vote_method,
  election_2_party text REFERENCES political_parties (code),
  election_3_vote_method vote_method,
  election_3_party text REFERENCES political_parties (code),
  election_4_vote_method vote_method,
  election_4_party text REFERENCES political_parties (code),
  election_5_vote_method vote_method,
  election_5_party text REFERENCES political_parties (code),
  election_6_vote_method vote_method,
  election_6_party text REFERENCES political_parties (code),
  election_7_vote_method vote_method,
  election_7_party text REFERENCES political_parties (code),
  election_8_vote_method vote_method,
  election_8_party text REFERENCES political_parties (code),
  election_9_vote_method vote_method,
  election_9_party text REFERENCES political_parties (code),
  election_10_vote_method vote_method,
  election_10_party text REFERENCES political_parties (code),
  election_11_vote_method vote_method,
  election_11_party text REFERENCES political_parties (code),
  election_12_vote_method vote_method,
  election_12_party text REFERENCES political_parties (code),
  election_13_vote_method vote_method,
  election_13_party text REFERENCES political_parties (code),
  election_14_vote_method vote_method,
  election_14_party text REFERENCES political_parties (code),
  election_15_vote_method vote_method,
  election_15_party text REFERENCES political_parties (code),
  election_16_vote_method vote_method,
  election_16_party text REFERENCES political_parties (code),
  election_17_vote_method vote_method,
  election_17_party text REFERENCES political_parties (code),
  election_18_vote_method vote_method,
  election_18_party text REFERENCES political_parties (code),
  election_19_vote_method vote_method,
  election_19_party text REFERENCES political_parties (code),
  election_20_vote_method vote_method,
  election_20_party text REFERENCES political_parties (code),
  election_21_vote_method vote_method,
  election_21_party text REFERENCES political_parties (code),
  election_22_vote_method vote_method,
  election_22_party text REFERENCES political_parties (code),
  election_23_vote_method vote_method,
  election_23_party text REFERENCES political_parties (code),
  election_24_vote_method vote_method,
  election_24_party text REFERENCES political_parties (code),
  election_25_vote_method vote_method,
  election_25_party text REFERENCES political_parties (code),
  election_26_vote_method vote_method,
  election_26_party text REFERENCES political_parties (code),
  election_27_vote_method vote_method,
  election_27_party text REFERENCES political_parties (code),
  election_28_vote_method vote_method,
  election_28_party text REFERENCES political_parties (code),
  election_29_vote_method vote_method,
  election_29_party text REFERENCES political_parties (code),
  election_30_vote_method vote_method,
  election_30_party text REFERENCES political_parties (code),
  election_31_vote_method vote_method,
  election_31_party text REFERENCES political_parties (code),
  election_32_vote_method vote_method,
  election_32_party text REFERENCES political_parties (code),
  election_33_vote_method vote_method,
  election_33_party text REFERENCES political_parties (code),
  election_34_vote_method vote_method,
  election_34_party text REFERENCES political_parties (code),
  election_35_vote_method vote_method,
  election_35_party text REFERENCES political_parties (code),
  election_36_vote_method vote_method,
  election_36_party text REFERENCES political_parties (code),
  election_37_vote_method vote_method,
  election_37_party text REFERENCES political_parties (code),
  election_38_vote_method vote_method,
  election_38_party text REFERENCES political_parties (code),
  election_39_vote_method vote_method,
  election_39_party text REFERENCES political_parties (code),
  election_40_vote_method vote_method,
  election_40_party text REFERENCES political_parties (code),
  home_phone text,
  county text,
  mail_country text
);
